#!/usr/bin/env bash
# Verify and document DNS for the three-box chain (secretcon.local -> ASREP DC).
#
# Usage:
#   ./scripts/proxmox/configure-chain-dns.sh [--check-only]
#
# Environment:
#   CHAIN_DC_IP     ASREP DC IP (default 192.168.61.52)
#   CHAIN_DOMAIN    default secretcon.local

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# shellcheck source=../lib/chain_env.sh
source "${REPO_ROOT}/scripts/lib/chain_env.sh"

CHECK_ONLY=0
while [ $# -gt 0 ]; do
  case "$1" in
    --check-only) CHECK_ONLY=1; shift ;;
    -h|--help)
      sed -n '3,12p' "$0"
      exit 0
      ;;
    *) echo "[!] unknown flag: $1" >&2; exit 2 ;;
  esac
done

ENV_OUT="${REPO_ROOT}/.tmp/chain-dns.env"
mkdir -p "$(dirname "$ENV_OUT")"
cat > "$ENV_OUT" <<EOF
# Generated by configure-chain-dns.sh on $(date -u +%FT%TZ)
CHAIN_DOMAIN=${CHAIN_DOMAIN}
CHAIN_DC_IP=${CHAIN_DC_IP}
# Use on challenge VMs (proxmox-static-ip.txt DNS field):
#   ${CHAIN_DC_IP},${CHAIN_WAZUH_IP}
EOF

echo "[*] Chain DNS target: ${CHAIN_DOMAIN} -> ${CHAIN_DC_IP}"
echo "    wrote ${ENV_OUT}"

if command -v dig >/dev/null 2>&1; then
  if dig +time=2 +tries=1 "@${CHAIN_DC_IP}" "${CHAIN_DOMAIN}" SOA +short 2>/dev/null | grep -q .; then
    echo "[+] dig @${CHAIN_DC_IP} ${CHAIN_DOMAIN} SOA: OK"
  else
    echo "[!] dig @${CHAIN_DC_IP} ${CHAIN_DOMAIN} SOA: no answer (DC may still be promoting)"
  fi
elif command -v nslookup >/dev/null 2>&1; then
  if nslookup "${CHAIN_DOMAIN}" "${CHAIN_DC_IP}" 2>/dev/null | grep -q "Address:"; then
    echo "[+] nslookup ${CHAIN_DOMAIN} @${CHAIN_DC_IP}: OK"
  else
    echo "[!] nslookup ${CHAIN_DOMAIN} @${CHAIN_DC_IP}: failed"
  fi
else
  echo "[~] install dig or nslookup for live DNS checks"
fi

if [ "$CHECK_ONLY" -eq 1 ]; then
  exit 0
fi

cat <<DOC

Operator notes (OPNsense VM 100 or upstream resolver):
  Host override: ${CHAIN_DOMAIN} -> ${CHAIN_DC_IP}
  Optional: _ldap._tcp.${CHAIN_DOMAIN} SRV -> ${CHAIN_DC_IP}:389

Challenge VM static DNS (already set by deploy-cysvuln.sh / deploy-asrep.sh):
  DNS servers: ${CHAIN_DC_IP}, ${CHAIN_WAZUH_IP}

Verify from Kali on vmbr1:
  dig @${CHAIN_DC_IP} ${CHAIN_DOMAIN} SOA
  impacket-GetNPUsers ${CHAIN_DOMAIN}/ -no-pass -dc-ip ${CHAIN_DC_IP} -usersfile /dev/stdin <<< enite

DOC
