#!/usr/bin/env bash
# Discover live Proxmox CysVuln VM and render Ansible inventory fragment.
#
# Queries VMID (default 118) on the Proxmox host, probes candidate build/campaign
# IPs for HTTP :80 (EFS) and WinRM :5985 (from the Proxmox host), and writes
# ansible/inventory/proxmox.discovered.yml.
#
# Usage:
#   ./scripts/proxmox/discover-proxmox-inventory-cysvuln.sh [--stdout] [--vm-id 118]
#
# Exit 0 when a reachable CysVuln host is found; exit 1 otherwise.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${REPO_ROOT}"

STDOUT_ONLY=0
CYSVULN_VM_ID_CLI=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --stdout)   STDOUT_ONLY=1; shift ;;
        --vm-id)    CYSVULN_VM_ID_CLI="$2"; shift 2 ;;
        -h|--help)
            sed -n '3,12p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "[!] unknown flag: $1" >&2; exit 2 ;;
    esac
done

# shellcheck source=scripts/lib/proxmox-ssh.sh
source "${REPO_ROOT}/scripts/lib/proxmox-ssh.sh"
proxmox_load_env

CYSVULN_VM_ID="${CYSVULN_VM_ID_CLI:-${CYSVULN_PROXMOX_VMID:-118}}"
CHAIN_CYSVULN_IP="${CHAIN_CYSVULN_IP:-192.168.61.51}"
CYSVULN_BUILD_IP="${CYSVULN_PROXMOX_IP:-192.168.60.57}"
OUT_FILE="${REPO_ROOT}/ansible/inventory/proxmox.discovered.yml"

probe_winrm_from_pve() {
    local ip="$1"
    pxssh "timeout 2 bash -c '</dev/tcp/${ip}/5985'" 2>/dev/null
}

probe_http_efs() {
    local ip="$1"
    curl -sf --connect-timeout 2 "http://${ip}/" 2>/dev/null \
        | head -1 | grep -qi 'Easy File Sharing' && return 0
    return 1
}

qm_status="$(pxssh "qm status ${CYSVULN_VM_ID} 2>/dev/null" || true)"
if [[ -z "${qm_status}" ]]; then
    echo "[!] VMID ${CYSVULN_VM_ID} not found on ${PROXMOX_HOST}" >&2
    exit 1
fi

qm_config="$(pxssh "qm config ${CYSVULN_VM_ID}" 2>/dev/null || true)"
proxmox_bridge=""
if [[ -n "${qm_config}" ]]; then
    proxmox_bridge="$(printf '%s\n' "${qm_config}" | sed -n 's/^net0:.*bridge=\([^,]*\).*/\1/p' | head -1)"
fi
proxmox_bridge="${proxmox_bridge:-unknown}"

echo "[*] Proxmox VMID ${CYSVULN_VM_ID}: ${qm_status%%$'\n'*}"
echo "    net0 bridge: ${proxmox_bridge}"

DISCOVERED_IP=""
for candidate in "${CYSVULN_BUILD_IP}" "${CHAIN_CYSVULN_IP}"; do
    [[ -z "${candidate}" ]] && continue
    if probe_winrm_from_pve "${candidate}"; then
        DISCOVERED_IP="${candidate}"
        echo "[+] WinRM reachable from Proxmox at ${candidate}:5985"
        break
    fi
    if probe_http_efs "${candidate}"; then
        DISCOVERED_IP="${candidate}"
        echo "[+] EFS HTTP reachable at ${candidate}:80 (WinRM not probed open from PVE)"
        break
    fi
    echo "[.] ${candidate}: WinRM/EFS not reachable from Proxmox (is the VM running?)"
done

if [[ -z "${DISCOVERED_IP}" ]]; then
  echo "[*] Scanning vmbr0 for EFS v6.9 banner..."
  scan_out="$(pxssh "for i in \$(seq 1 254); do
    r=\$(curl -sf --connect-timeout 1 http://192.168.60.\$i/ 2>/dev/null | head -1)
    echo \"\$i \$r\"
  done" 2>/dev/null | grep -i 'Easy File Sharing' | head -1 || true)"
  if [[ -n "${scan_out}" ]]; then
    octet="$(printf '%s' "${scan_out}" | awk '{print $1}')"
    DISCOVERED_IP="192.168.60.${octet}"
    echo "[+] Discovered EFS at ${DISCOVERED_IP} via subnet scan"
  fi
fi

if [[ -z "${DISCOVERED_IP}" ]]; then
    echo "[!] No candidate answered (${CYSVULN_BUILD_IP}, ${CHAIN_CYSVULN_IP})" >&2
    exit 1
fi

if [[ "${proxmox_bridge}" == "vmbr0" && "${DISCOVERED_IP}" == "${CHAIN_CYSVULN_IP}" ]]; then
    echo "[i] VM on vmbr0 but campaign IP ${CHAIN_CYSVULN_IP} responded — metadata may be stale"
elif [[ "${proxmox_bridge}" == "vmbr0" && "${DISCOVERED_IP}" != "${CHAIN_CYSVULN_IP}" ]]; then
    echo "[i] VM on vmbr0 build IP ${DISCOVERED_IP}; campaign target is ${CHAIN_CYSVULN_IP} on vmbr1"
fi

INV_CONTENT="# Generated by scripts/proxmox/discover-proxmox-inventory-cysvuln.sh — do not edit.
all:
  children:
    windows:
      children:
        cysvuln:
          hosts:
            cysvuln-proxmox:
              ansible_host: \"${DISCOVERED_IP}\"
              proxmox_vmid: ${CYSVULN_VM_ID}
              proxmox_bridge: \"${proxmox_bridge}\"
              wazuh_agent_group: cysvuln
"

if [[ "${STDOUT_ONLY}" -eq 1 ]]; then
    printf '%s' "${INV_CONTENT}"
else
    mkdir -p "$(dirname "${OUT_FILE}")"
    printf '%s' "${INV_CONTENT}" > "${OUT_FILE}"
    echo "[+] Wrote ${OUT_FILE}"
    echo "    ansible_host=${DISCOVERED_IP}"
fi

exit 0
