#!/usr/bin/env bash
# Shared env defaults for the three-box campaign (CysVuln -> EWS -> ASREP DC).
# shellcheck disable=SC2034

CHAIN_CYSVULN_IP="${CHAIN_CYSVULN_IP:-${CYSVULN_PROXMOX_IP:-192.168.61.51}}"
CHAIN_EWS_IP="${CHAIN_EWS_IP:-192.168.61.20}"
CHAIN_DC_IP="${CHAIN_DC_IP:-${ASREP_PROXMOX_IP:-192.168.61.52}}"
CHAIN_WAZUH_IP="${CHAIN_WAZUH_IP:-${WAZUH_MANAGER_HOST:-192.168.61.10}}"
CHAIN_DOMAIN="${CHAIN_DOMAIN:-secretcon.local}"

SECRETCON_SHARED_LOCAL_ADMIN_PASSWORD="${SECRETCON_SHARED_LOCAL_ADMIN_PASSWORD:-${ADMIN_PW:-PizzaMan123!}}"
export SECRETCON_SHARED_LOCAL_ADMIN_PASSWORD
export ADMIN_PW="${ADMIN_PW:-$SECRETCON_SHARED_LOCAL_ADMIN_PASSWORD}"

SECRETCON_DC_USER_FLAG="${SECRETCON_DC_USER_FLAG:-${SECRETCON_ASREP_FLAG:-asrep-user-flag-placeholder}}"
SECRETCON_DC_ROOT_FLAG="${SECRETCON_DC_ROOT_FLAG:-asrep-root-flag-placeholder}"
SECRETCON_ASREP_ENITE_DA="${SECRETCON_ASREP_ENITE_DA:-1}"
