#!/usr/bin/env bash
# shellcheck shell=bash
#
# loop_lib.sh -- shared helpers for the observability / capture-loop
# orchestrators (observability-loop.sh, baseline-snapshot.sh,
# run-baseline-tour.sh, stress-campaign.sh).
#
# Source from a caller after setting set -uo pipefail (or -euo, the
# helpers are tolerant of either):
#
#   REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
#   . "${REPO_ROOT}/scripts/lib/loop_lib.sh"
#
# Helpers expect the caller to populate the env vars they reference
# (QCOW, PIDFILE, WINRM_PORT, ADMIN_USER, ADMIN_PW, etc.) before invoking
# the function. This keeps the lib free of "magic" hardcoded defaults --
# the orchestrators are the source of truth for credentials and paths.

# -----------------------------------------------------------------------------
# Flag-token bookkeeping
# -----------------------------------------------------------------------------

# loop_gen_or_reuse_flags RUN_ID OUT_DIR
#
# Ensures OUT_DIR/flags.env exists for the given RUN_ID. If the file is
# already present we reuse it (regenerating tokens after a Packer rebuild
# would desync the on-disk flags from what is baked into the qcow2).
# Otherwise we write fresh hex-12 tokens with mode 0600.
#
# Side effects:
#   - mkdir -p OUT_DIR
#   - writes / sources OUT_DIR/flags.env
#   - exports SECRETCON_USER_FLAG, SECRETCON_ROOT_FLAG, SECRETCON_RUN_ID
#   - echoes the absolute path to flags.env on stdout (so callers can
#     capture it with `FLAGS_ENV=$(loop_gen_or_reuse_flags ...)`).
loop_gen_or_reuse_flags() {
    local run_id="$1" out_dir="$2"
    mkdir -p "$out_dir"
    local flags_env="${out_dir}/flags.env"

    if [ -f "$flags_env" ]; then
        echo "[*] flags.env already exists, reusing: ${flags_env}" >&2
        # shellcheck disable=SC1090
        . "$flags_env"
        echo "    user: ${SECRETCON_USER_FLAG:-<missing>}" >&2
        echo "    root: ${SECRETCON_ROOT_FLAG:-<missing>}" >&2
        export SECRETCON_USER_FLAG SECRETCON_ROOT_FLAG SECRETCON_RUN_ID
        echo "$flags_env"
        return 0
    fi

    local user_tok root_tok
    user_tok=$(openssl rand -hex 12)
    root_tok=$(openssl rand -hex 12)

    cat > "$flags_env" <<EOF
# Generated by scripts/lib/loop_lib.sh::loop_gen_or_reuse_flags on $(date -u +%FT%TZ)
# Run ID: ${run_id}
SECRETCON_USER_FLAG=flag{user-${user_tok}}
SECRETCON_ROOT_FLAG=flag{root-${root_tok}}
SECRETCON_RUN_ID=${run_id}
EOF
    chmod 0600 "$flags_env"

    # shellcheck disable=SC1090
    . "$flags_env"
    export SECRETCON_USER_FLAG SECRETCON_ROOT_FLAG SECRETCON_RUN_ID

    echo "[*] flags.env written: ${flags_env}" >&2
    echo "    user: ${SECRETCON_USER_FLAG}" >&2
    echo "    root: ${SECRETCON_ROOT_FLAG}" >&2
    echo "$flags_env"
}

# loop_gen_or_reuse_asrep_flags RUN_ID OUT_DIR
#
# Same as loop_gen_or_reuse_flags but for the single ASREP demo flag.
loop_gen_or_reuse_asrep_flags() {
    local run_id="$1" out_dir="$2"
    mkdir -p "$out_dir"
    local flags_env="${out_dir}/flags.env"

    if [ -f "$flags_env" ]; then
        echo "[*] flags.env already exists, reusing: ${flags_env}" >&2
        # shellcheck disable=SC1090
        . "$flags_env"
        echo "    flag: ${SECRETCON_ASREP_FLAG:-<missing>}" >&2
        export SECRETCON_ASREP_FLAG SECRETCON_RUN_ID
        echo "$flags_env"
        return 0
    fi

    local tok
    tok=$(openssl rand -hex 12)
    cat > "$flags_env" <<EOF
# Generated by scripts/lib/loop_lib.sh::loop_gen_or_reuse_asrep_flags on $(date -u +%FT%TZ)
# Run ID: ${run_id}
SECRETCON_ASREP_FLAG=flag{asrep-${tok}}
SECRETCON_RUN_ID=${run_id}
EOF
    chmod 0600 "$flags_env"
    # shellcheck disable=SC1090
    . "$flags_env"
    export SECRETCON_ASREP_FLAG SECRETCON_RUN_ID
    echo "[*] flags.env written: ${flags_env}" >&2
    echo "    flag: ${SECRETCON_ASREP_FLAG}" >&2
    echo "$flags_env"
}

# -----------------------------------------------------------------------------
# QEMU VM lifecycle
# -----------------------------------------------------------------------------

# loop_winrm_stop_computer PORT ADMIN_PW
#
# Best-effort Stop-Computer via Administrator WinRM. Failure is silent;
# the caller's loop_stop_vm escalates to SIGTERM + pkill as a fallback.
loop_winrm_stop_computer() {
    local port="$1" pw="$2"
    python3 - "$port" "$pw" <<'PY' || true
import sys, winrm
port, pw = sys.argv[1:3]
s = winrm.Session(f"http://127.0.0.1:{port}/wsman",
                  auth=("Administrator", pw), transport="ntlm")
try:
    s.run_ps("Stop-Computer -Force")
except Exception:
    pass
PY
}

# loop_stop_vm
#
# Graceful Stop-Computer via WinRM, then SIGTERM the QEMU pid in PIDFILE
# if it does not exit in time. Belt-and-suspenders pkill catches the case
# where the pidfile is stale but a QEMU process is still holding the qcow2
# write lock (critical for snapshot revert to succeed on the next iter).
#
# Reads env: PIDFILE, WINRM_PORT, ADMIN_PW, QCOW
# Side effects: kills QEMU, rm -f "$PIDFILE"
loop_stop_vm() {
    local pidfile="${PIDFILE:-/tmp/cysvuln-local.pid}"
    local port="${WINRM_PORT:-15985}"
    local pw="${ADMIN_PW:-PizzaMan123!}"
    local qcow="${QCOW:-}"

    if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile" 2>/dev/null)" 2>/dev/null; then
        loop_winrm_stop_computer "$port" "$pw"
        local deadline
        deadline=$(( $(date +%s) + 60 ))
        while [ "$(date +%s)" -lt "$deadline" ]; do
            if [ ! -f "$pidfile" ] || ! kill -0 "$(cat "$pidfile" 2>/dev/null)" 2>/dev/null; then
                break
            fi
            sleep 2
        done
        if [ -f "$pidfile" ] && kill -0 "$(cat "$pidfile" 2>/dev/null)" 2>/dev/null; then
            kill "$(cat "$pidfile")" 2>/dev/null || true
            sleep 3
        fi
    fi

    if [ -n "$qcow" ] && pgrep -f "qemu-system-x86_64.*$(basename "$qcow")" >/dev/null 2>&1; then
        pkill -f "qemu-system-x86_64.*$(basename "$qcow")" 2>/dev/null || true
        sleep 3
    fi
    rm -f "$pidfile"
}

# loop_revert_snapshot QCOW SNAP_NAME
loop_revert_snapshot() {
    local qcow="$1" snap="$2"
    qemu-img snapshot -a "$snap" "$qcow"
}

# loop_take_snapshot_if_missing QCOW SNAP_NAME
#
# Idempotent: if a snapshot with this name already exists, list and skip.
# Exit non-zero on qemu-img failure.
loop_take_snapshot_if_missing() {
    local qcow="$1" snap="$2"
    if qemu-img snapshot -l "$qcow" 2>/dev/null | awk '{print $2}' | grep -Fxq "$snap"; then
        echo "[*] Snapshot '${snap}' already exists on ${qcow}; nothing to do" >&2
        qemu-img snapshot -l "$qcow" >&2
        return 0
    fi
    qemu-img snapshot -c "$snap" "$qcow"
    qemu-img snapshot -l "$qcow" >&2
}

# -----------------------------------------------------------------------------
# WinRM markers for unambiguous timeline slicing
# -----------------------------------------------------------------------------

# loop_winrm_marker KIND PHASE_ID [ITER]
#
# Emits a `SECRETCON-PHASE-<id>-<kind>` (or `SECRETCON-ITER-<iter>-PHASE-<id>-<kind>`
# when ITER is non-empty) via `cmd /c echo` over Administrator WinRM. The
# resulting Sysmon EID 1 has a unique commandLine so any dataset consumer
# can grep the event boundary even when iteration windows overlap.
#
# Reads env: WINRM_PORT, ADMIN_USER, ADMIN_PW, TARGET (defaults 127.0.0.1)
loop_winrm_marker() {
    local kind="$1" phase_id="$2" iter="${3:-}"
    local target="${TARGET:-127.0.0.1}"
    local port="${WINRM_PORT:-15985}"
    local user="${ADMIN_USER:-Administrator}"
    local pw="${ADMIN_PW:-PizzaMan123!}"

    python3 - "$target" "$port" "$user" "$pw" "$kind" "$phase_id" "$iter" \
        <<'PY' 2>/dev/null || true
import sys, winrm
target, port, user, pw, kind, pid, iter_n = sys.argv[1:8]
s = winrm.Session(f"http://{target}:{port}/wsman",
                  auth=(user, pw), transport="ntlm")
if iter_n:
    s.run_cmd("cmd", ["/c", f"echo SECRETCON-ITER-{iter_n}-PHASE-{pid}-{kind}"])
else:
    s.run_cmd("cmd", ["/c", f"echo SECRETCON-PHASE-{pid}-{kind}"])
PY
}
