#!/usr/bin/env bash
set -euo pipefail

# Emit a randomized flags.env for an observability-loop run. Persisted
# under artifacts/cysvuln/observability-loop/<run-id>/ (gitignored) so
# the blue-team report can later cite the exact tokens that should
# appear in Sysmon EID 11 / cmd.exe argv events.
#
# Usage:
#   ./scripts/observability/gen-flags.sh [--run-id ID] [--out-dir DIR]
#
# Outputs to stdout the absolute path to the generated flags.env so
# upstream callers can capture it:
#
#   FLAGS_ENV=$(./scripts/observability/gen-flags.sh --run-id "$RUN_ID")
#   . "$FLAGS_ENV"
#   echo "$SECRETCON_USER_FLAG"

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

RUN_ID=""
OUT_DIR=""
while [ $# -gt 0 ]; do
    case "$1" in
        --run-id) RUN_ID="$2"; shift 2 ;;
        --out-dir) OUT_DIR="$2"; shift 2 ;;
        -h|--help) sed -n '3,17p' "$0"; exit 0 ;;
        *) echo "[!] unknown flag: $1" >&2; exit 2 ;;
    esac
done

if [ -z "$RUN_ID" ]; then
    RUN_ID="loop-$(date -u +%Y%m%dT%H%M%SZ)"
fi
if [ -z "$OUT_DIR" ]; then
    OUT_DIR="${REPO_ROOT}/artifacts/cysvuln/observability-loop/${RUN_ID}"
fi

mkdir -p "$OUT_DIR"

FLAGS_ENV="${OUT_DIR}/flags.env"

# Idempotent: if flags.env already exists for this run-id, reuse it.
# Regenerating new tokens after a Packer rebuild would silently
# desynchronize the on-disk flags from what's baked into the qcow2.
if [ -f "$FLAGS_ENV" ]; then
    echo "[*] flags.env already exists, reusing: ${FLAGS_ENV}" >&2
    # shellcheck disable=SC1090
    . "$FLAGS_ENV"
    echo "    user: ${SECRETCON_USER_FLAG}" >&2
    echo "    root: ${SECRETCON_ROOT_FLAG}" >&2
    echo "$FLAGS_ENV"
    exit 0
fi

USER_TOKEN=$(openssl rand -hex 12)
ROOT_TOKEN=$(openssl rand -hex 12)

cat > "$FLAGS_ENV" <<EOF
# Generated by scripts/observability/gen-flags.sh on $(date -u +%FT%TZ)
# Run ID: ${RUN_ID}
SECRETCON_USER_FLAG=flag{user-${USER_TOKEN}}
SECRETCON_ROOT_FLAG=flag{root-${ROOT_TOKEN}}
SECRETCON_RUN_ID=${RUN_ID}
EOF
chmod 0600 "$FLAGS_ENV"

echo "[*] flags.env written: ${FLAGS_ENV}" >&2
echo "    user: flag{user-${USER_TOKEN}}" >&2
echo "    root: flag{root-${ROOT_TOKEN}}" >&2
echo "$FLAGS_ENV"
